server:
  port: 0
spring:
  application:
    name: itemServer
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    stream:
      bindings:
        updateItemTopic:
          group: ${spring.application.name}
          destination: updateItemTopic
          consumer:
            concurrency: 10
            maxAttempts: 1
        changedItemTopic:
          destination: changedItemTopic
      rabbit:
        bindings:
          updateItemTopic:
            consumer:
              autoBindDlq: true
              republishToDlq: true
              requeueRejected: true
              dlqTtl: 5000
              dlqDeadLetterExchange:
